name:
  sofa-client
services:
  sofa-client:
    container_name: sofa-client-dev
    image: sofa-client:dev
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 2048M
    networks:
      nginx-network:  
        aliases: 
        - sofa-client-dev
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone:ro
      - type: bind
        source: /etc/localtime
        target: /etc/localtime:ro
      - type: bind
        source: /home/code/sofa-client/src
        target: /app/src
      - type: bind
        source: /home/code/sofa-client/.env.development
        target: /app/.env.development

networks:
  nginx-network:
    external: true
